#!/bin/bash

function install_ra() {
    # Modify or remove this as required by your application.
  if [ -n "${INSTALL_URL_RA}" ]; then
    # If we've been given and installer URL derive the filename
    INSTALL_EXE_RA=$(basename "${INSTALL_URL_RA//\?*/}")
    # Downloads a file with progress using wget and yad
    wget "${INSTALL_URL_RA}" -O "${TMPDIR}/${INSTALL_EXE_RA}" 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/' | \
    yad --progress --title="${INSTALL_EXE_RA}" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape 2>/dev/null
    # Installs the wine application
    env WINEARCH="${WINEARCH}" WINEPREFIX="${WINEPREFIX}" "${WINELOADER}" "${TMPDIR}/${INSTALL_EXE_RA}"
    # Create Game dir without space & move files to it so that find command finds game exe properly
    mkdir -p "$WINEPREFIX/drive_c/Games/RedAlert"
    cp -r --preserve=mode "$WINEPREFIX/drive_c/Games/Red Alert/"* "$WINEPREFIX/drive_c/Games/RedAlert"
    # Removes the cached installers & files
    rm -rf "$WINEPREFIX/drive_c/Games/Red Alert/"
    rm -v "${TMPDIR}/${INSTALL_EXE_RA}"
    rm -v "${XDG_CACHE_HOME}/wine/${MONO_MSI}" 2>/dev/null
    rm -r "${XDG_CACHE_HOME}/winetricks" 2>/dev/null
  fi
}

function install_cnc() {
    # Modify or remove this as required by your application.
  if [ -n "${INSTALL_URL_CNC}" ]; then
    # If we've been given and installer URL derive the filename
    INSTALL_EXE_CNC=$(basename "${INSTALL_URL_CNC//\?*/}")
    # Downloads a file with progress using wget and yad
    wget "${INSTALL_URL_CNC}" -O "${TMPDIR}/${INSTALL_EXE_CNC}" 2>&1 | \
    perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/' | \
    yad --progress --title="${INSTALL_EXE_CNC}" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape 2>/dev/null
    # Installs the wine application
    env WINEARCH="${WINEARCH}" WINEPREFIX="${WINEPREFIX}" "${WINELOADER}" "${TMPDIR}/${INSTALL_EXE_CNC}" /silent
    # Copy game files to $WINEPREFIX
    mkdir -p "${WINEPREFIX}/drive_c/Games/CnCNet/"
    cp -r --preserve=mode "${TMPDIR}/RedAlert1_Online" "${WINEPREFIX}/drive_c/Games/CnCNet/"
    # Remove Game install from tmp
    rm -r "${TMPDIR}/RedAlert1_Online"
    # Removes the cached installers
    rm -v "${TMPDIR}/${INSTALL_EXE_CNC}"
    rm -v "${XDG_CACHE_HOME}/wine/${MONO_MSI}" 2>/dev/null
    rm -r "${XDG_CACHE_HOME}/winetricks" 2>/dev/null
  fi
}
  action=$(yad --width 400 --entry --title "C&C: Red Alert" \
      --center \
      --width=400 \
      --button="Install:0" --button="Exit:1" \
      --text "Select Game Version Type:" \
      --entry-text \
      "Full Game (Singleplayer + Multiplayer)" "Multiplayer" 2>/dev/null)
  ret=$?

  [[ $ret -eq 1 ]] && exit 0

  case $action in
      Full*) cmd=$(install_ra) ;;
      Multi*) cmd=$(install_cnc) ;;
      *) exit 1 ;;    
  esac

  eval $cmd 2>/dev/null