name: cncra
title: C&C Red Alert (WINE)
version: '1.0'
summary: C&C Red Alert is a real-time strategy game.
description: |
 Command & Conquer: Red Alert is a real-time strategy game and second release in the Command & Conquer series, having been released in October of 1996. it is also the first game in the Red Alert sub-series that takes an alternative path/story of the main Command & Conquer series.

 C&C: Red Alert is set prior to the events in Command & Conquer in an alternative history where the Soviet Union has invaded Eastern Europe and started a new war against the remaining European countries and the United States.

 When the game was released in 1996 it was praised by fans and critics alike for its intuitive user interface and gameplay that was ahead of its time. New, groundbreaking features introduced with the release of Command & Conquer Red Alert included the ability to queue commands, create and assign multiple units into a single group by a simple drag and select, as well as multiple factions with different strengths and weaknesses. These features have since become standard for the genre.

grade: stable
confinement: strict
architectures:
  - build-on: amd64
base: core22

plugs:
  shmem:
    interface: shared-memory
    private: true
  wine-runtime-c22:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime-core22
  wine-7-stable-c22:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-7-stable-core22

environment:
  WINEDLLOVERRIDES: "mshtml="    # Prevent pop-ups about Wine Gecko
  WINEPREFIX: "$SNAP_USER_COMMON/.wine"
  WINEARCH: "win32"
  INSTALL_URL_RA: "https://downloads.cncnet.org/RA1installer.exe" # cncra full game setup
  INSTALL_URL_CNC: "https://downloads.cncnet.org/RedAlert1_Online_Installer.exe" # cncra multiplayer only setup
  TRICKS: "dotnet20"
  NO_AT_BRIDGE: 1
  DISABLE_WAYLAND: 1
  SOMMELIER_INSTALL_MONO: 1
  SOMMELIER_NO_THEME: 1

apps:
  cncra:
    extensions: [gnome]
    command: bin/sommelier run-exe
    environment:
      RUN_EXE: "$WINEPREFIX/drive_c/Games/CnCNet/RedAlert1_Online/RA1MPLauncher.exe"
      RUN_EXE_2: "$WINEPREFIX/drive_c/Games/RedAlert/RA95Launcher.exe"
    plugs:
      - shmem
      - home
      - network
      - network-bind

  wine:
    extensions: [gnome]
    command: bin/sommelier
    plugs:
      - shmem
      - home
      - network

  winetricks:
    extensions: [gnome]
    command: bin/sommelier winetricks
    plugs:
      - network

parts:
  cncra:
    plugin: nil
    source: ./snap/local/src
    override-build: |
      craftctl default
      set -ex
      mkdir -p sommelier/hooks ; mv pre-install sommelier/hooks ; cp -R -p sommelier $CRAFT_PART_INSTALL
    stage:
      - sommelier

  # The sommelier script helps you snap Windows applications using Wine. It
  # initializes and configures Wine and installs the Windows application.
  sommelier:
    plugin: make
    source: https://github.com/mmtrt/sommelier-core.git
    source-branch: "testc22"
    build-packages:
      - libc6-dev-i386
      - gcc-multilib
